### PR TITLE
Updated wfc

### PR DESCRIPTION
**Pull request by ojorgensen**
Updated wfc to work with the updated encodings, and to produced a specified number of agents.
Issues (will add these as an issue on github):
Do some kind of hyperparameter tuning for the weights for different board sizes / number of agents;
Incorporate Ugo’s and Randy’s fancy removal methods for when the wfc board has too many wires.

### CODE REVIEW

**Comment by ojorgensen** [comment]
> 

I'll sort out docstrings tomorrow!

It can be guaranteed (kind of): I added the galaxy brained removal method of "just get rid of all wires over the limit" when the method produces too many wires; and if it doesn't produce enough, I restart the process and change the weights to be more likely to include start / end points. This should mean that it will eventually produce enough wires, although I imagine it will work poorly when someone tries to generate an incredibly packed board.

**Review by mwolinska — APPROVED** [review]
Happy for you to merge and for you to go back to do docstrings later

**Comment by ojorgensen** [comment]
Added better docstrings

**Comment by ojorgensen** [comment]
cool! I'll merge now

**Pull request merged**
